
version: '3'
services:
  keycloak-database:
    container_name: "shanoir-keycloak-database"
    build: ./keycloak-database
    environment:
      - MYSQL_DATABASE=keycloak
    volumes:
      - "keycloak-database-data:/var/lib/mysql"
    ports:
      - "3309:3306"

  database:
    container_name: "shanoir-ms-database"
    build: ./database
    env_file:
      - ./variables.env
    volumes:
      - "database-data:/var/lib/mysql"
    ports:
     - "3308:3306"

volumes:
  keycloak-database-data:
  database-data:
